// Centralized content for MPG Solution LLC website
// Single source of truth for all text, services, FAQs, etc.

export const COMPANY = {
  name: "MPG Solution LLC",
  legalName: "MPG Solution LLC",
  tagline: "Strategic Digital Marketing for Growing Businesses",
  description: "A Wyoming-registered digital marketing company offering strategy, creative, paid social campaigns, lead generation, and performance-focused marketing support for businesses.",
  address: "30 N Gould St Ste R, Sheridan, WY 82801, USA",
  email: "admin@adsmpg.com",
  phone: "+1 315 961 3832",
  website: "www.adsmpg.com",
  nature: "Digital marketing and advertising services",
  founded: "Wyoming, USA",
  owner: "Owned and operated by MPG Solution LLC.",
};

export const SERVICES = [
  {
    id: "social-media-strategy",
    title: "Social Media Marketing Strategy",
    icon: "Share2",
    shortDesc: "Comprehensive social media strategies that align with your business goals and drive sustainable growth.",
    description: "We build tailored social media marketing strategies that go beyond posting — covering audience analysis, competitive positioning, content pillars, campaign calendars, and performance measurement frameworks.",
    forWhom: "Businesses that need a structured, goal-oriented social media marketing plan.",
    benefit: "Clear strategic direction, consistent brand presence, and measurable marketing outcomes.",
    approach: "We audit your current presence, analyze competitors, define target audiences, and build a phased strategy with KPIs and optimization milestones.",
  },
  {
    id: "meta-ads-management",
    title: "Meta Ads Management",
    icon: "Megaphone",
    shortDesc: "Full-service management of your Meta (Facebook & Instagram) advertising campaigns.",
    description: "End-to-end management of your advertising across Meta platforms. We handle strategy, setup, creative, targeting, optimization, and reporting — so you can focus on running your business.",
    forWhom: "Businesses that want expert, hands-off management of their Meta advertising.",
    benefit: "Professionally managed campaigns with continuous optimization and transparent reporting.",
    approach: "We take full ownership of your Meta ad accounts, from campaign architecture to daily monitoring and weekly optimizations.",
  },
  {
    id: "facebook-advertising",
    title: "Facebook Advertising",
    icon: "Facebook",
    shortDesc: "Strategic Facebook ad campaigns that reach your ideal customers and drive measurable results.",
    description: "We design, launch, and optimize Facebook advertising campaigns tailored to your business goals. From awareness to conversions, every campaign is built with data-driven targeting and compelling creatives.",
    forWhom: "Businesses looking to reach targeted audiences on the world's largest social platform.",
    benefit: "Increased brand visibility, qualified leads, and higher return on ad spend.",
    approach: "We start with audience research, create compelling ad creatives, set up precise targeting, and continuously optimize based on performance data.",
  },
  {
    id: "instagram-advertising",
    title: "Instagram Advertising",
    icon: "Instagram",
    shortDesc: "Visual-first Instagram campaigns that engage audiences and convert followers into customers.",
    description: "Leverage Instagram's visual platform with ads that captivate and convert. We handle everything from creative production to audience targeting and campaign optimization.",
    forWhom: "Brands and businesses that want to connect with engaged audiences through visual storytelling.",
    benefit: "Higher engagement rates, brand awareness, and direct-response conversions.",
    approach: "We craft scroll-stopping visuals, write persuasive copy, and deploy campaigns with precise audience segmentation across Instagram's ad placements.",
  },
  {
    id: "performance-marketing",
    title: "Performance Marketing Strategy",
    icon: "TrendingUp",
    shortDesc: "Data-driven marketing strategies focused on measurable outcomes and ROI.",
    description: "Our performance marketing approach ensures every dollar spent is tracked, measured, and optimized for maximum return. We build strategies that scale with your business.",
    forWhom: "Growth-focused businesses that want clear, measurable results from their marketing investment.",
    benefit: "Transparent reporting, optimized spend, and scalable campaign frameworks.",
    approach: "We analyze your current performance, identify growth opportunities, build measurement frameworks, and implement optimization cycles.",
  },
  {
    id: "lead-generation",
    title: "Lead Generation Campaigns",
    icon: "Users",
    shortDesc: "Targeted campaigns designed to fill your pipeline with qualified leads.",
    description: "Generate a steady flow of qualified leads through strategically designed ad campaigns. We create complete lead generation funnels from ad to form to follow-up.",
    forWhom: "Service businesses, B2B companies, and any business that relies on leads for growth.",
    benefit: "Consistent lead flow, lower cost per lead, and higher lead quality.",
    approach: "We design lead magnets, build landing pages, set up lead forms, and optimize the entire funnel for maximum lead volume and quality.",
  },
  {
    id: "creative-strategy",
    title: "Creative Strategy & Campaign Planning",
    icon: "Lightbulb",
    shortDesc: "Strategic creative planning that connects your brand message with campaign performance.",
    description: "Before any campaign launches, we develop a creative strategy that aligns your brand messaging, visual identity, and campaign objectives into a cohesive plan designed for impact.",
    forWhom: "Businesses that need strategic creative direction to elevate their marketing campaigns.",
    benefit: "Cohesive brand messaging, stronger ad performance, and a clear creative roadmap.",
    approach: "We conduct brand audits, develop creative briefs, plan campaign concepts, and map creative assets to each stage of the customer journey.",
  },
  {
    id: "ad-copywriting",
    title: "Ad Copywriting",
    icon: "PenTool",
    shortDesc: "Persuasive ad copy that speaks to your audience and drives action.",
    description: "Words matter. Our ad copywriting service delivers compelling headlines, body copy, and calls-to-action that resonate with your target audience and drive clicks, leads, and sales.",
    forWhom: "Businesses that need high-converting ad copy for social media campaigns.",
    benefit: "Higher click-through rates, improved ad relevance scores, and better conversion rates.",
    approach: "We research your audience, study competitor messaging, and craft copy variations for testing and optimization.",
  },
  {
    id: "creative-design",
    title: "Creative Design for Ads",
    icon: "Palette",
    shortDesc: "Scroll-stopping ad creatives designed to capture attention and convert.",
    description: "Stand out in crowded feeds with professionally designed ad creatives. We produce static images, carousels, and video-ready assets that align with your brand and campaign goals.",
    forWhom: "Businesses that need professional, on-brand creative assets for their ad campaigns.",
    benefit: "Improved ad performance, consistent brand presentation, and creative variety for testing.",
    approach: "We develop creative concepts, produce multiple variations, and test different visual approaches to find what resonates best with your audience.",
  },
  {
    id: "audience-targeting",
    title: "Audience Targeting",
    icon: "Target",
    shortDesc: "Precision audience targeting to reach the right people at the right time.",
    description: "Effective marketing starts with reaching the right audience. We build detailed audience profiles and targeting strategies using demographics, interests, behaviors, and lookalike audiences.",
    forWhom: "Businesses that want to maximize ad efficiency by reaching their most valuable potential customers.",
    benefit: "Reduced wasted spend, higher conversion rates, and more qualified leads.",
    approach: "We analyze your existing customer data, build custom and lookalike audiences, layer interest and behavior targeting, and refine based on campaign performance.",
  },
  {
    id: "campaign-optimization",
    title: "Campaign Setup & Optimization",
    icon: "Settings",
    shortDesc: "Expert campaign management from setup to ongoing performance optimization.",
    description: "We handle the technical setup of your marketing campaigns and provide ongoing optimization to ensure peak performance. From pixel installation to bid strategy, every detail is managed.",
    forWhom: "Businesses that want hands-off campaign management with expert-level optimization.",
    benefit: "Properly structured campaigns, ongoing performance improvements, and time savings.",
    approach: "We set up tracking, configure campaigns according to best practices, monitor performance daily, and make data-driven adjustments to improve results.",
  },
  {
    id: "remarketing",
    title: "Remarketing & Retargeting Campaigns",
    icon: "RefreshCw",
    shortDesc: "Re-engage visitors and past customers with strategic remarketing campaigns.",
    description: "Not every customer converts on the first visit. Our remarketing campaigns bring back interested prospects with tailored messaging, keeping your brand top-of-mind and driving conversions.",
    forWhom: "Businesses with website traffic or existing customer lists that want to improve conversion rates.",
    benefit: "Higher conversion rates, improved customer retention, and better return on existing traffic.",
    approach: "We segment your audiences based on behavior, create tailored ad sequences, and optimize frequency and messaging for maximum impact.",
  },
  {
    id: "conversion-funnel",
    title: "Conversion Funnel Strategy",
    icon: "Filter",
    shortDesc: "Full-funnel marketing strategies that guide prospects from awareness to purchase.",
    description: "We design and optimize complete conversion funnels — from first impression to final action. Every stage is mapped, measured, and refined for maximum throughput.",
    forWhom: "Businesses that want a systematic approach to turning prospects into paying customers.",
    benefit: "Higher conversion rates at every funnel stage, reduced drop-off, and improved ROI.",
    approach: "We map your customer journey, identify conversion bottlenecks, design funnel-specific campaigns, and implement stage-by-stage optimization.",
  },
  {
    id: "ecommerce-advertising",
    title: "E-commerce Advertising Support",
    icon: "ShoppingCart",
    shortDesc: "Drive online sales with targeted e-commerce advertising strategies.",
    description: "Boost your online store's revenue with advertising strategies built for e-commerce. We optimize product catalogs, dynamic ads, and retargeting campaigns to maximize sales.",
    forWhom: "Online stores and e-commerce businesses looking to increase sales through paid advertising.",
    benefit: "Higher ROAS, increased order volume, and improved customer acquisition costs.",
    approach: "We set up product catalogs, implement dynamic retargeting, create prospecting campaigns, and optimize for purchase conversions.",
  },
  {
    id: "landing-page-support",
    title: "Landing Page & Creative Support",
    icon: "Layout",
    shortDesc: "Conversion-optimized landing pages that turn ad traffic into results.",
    description: "Your ads are only as good as where they lead. We provide landing page strategy and creative support to ensure your ad traffic converts into leads, sales, or sign-ups.",
    forWhom: "Businesses running ad campaigns that need high-converting landing experiences.",
    benefit: "Higher conversion rates, better user experience, and improved campaign ROI.",
    approach: "We audit existing pages, recommend improvements, and design conversion-focused landing experiences aligned with your ad campaigns.",
  },
  {
    id: "marketing-consultation",
    title: "Marketing Consultation",
    icon: "MessageCircle",
    shortDesc: "Expert digital marketing guidance to help you make smarter growth decisions.",
    description: "Get strategic marketing advice from experienced professionals. Whether you need a second opinion, a fresh perspective, or a complete marketing review, we provide actionable insights.",
    forWhom: "Business owners and marketing teams that need expert guidance without full-service management.",
    benefit: "Clear strategic direction, actionable recommendations, and confidence in your marketing decisions.",
    approach: "We review your current marketing, identify opportunities, and deliver a prioritized action plan you can implement immediately.",
  },
  {
    id: "campaign-audit",
    title: "Campaign Audit & Performance Review",
    icon: "ClipboardCheck",
    shortDesc: "In-depth review of your existing campaigns with actionable improvement recommendations.",
    description: "Our campaign audit service provides a thorough analysis of your current advertising campaigns, identifying what's working, what's not, and where the biggest improvement opportunities lie.",
    forWhom: "Businesses already running campaigns that want an independent performance review.",
    benefit: "Clear understanding of campaign health, specific improvement actions, and potential cost savings.",
    approach: "We analyze campaign structure, targeting, creatives, bidding, and performance data, then deliver a detailed report with prioritized recommendations.",
  },
  {
    id: "brand-messaging",
    title: "Brand Messaging Support",
    icon: "Type",
    shortDesc: "Clarify and strengthen your brand voice for more impactful marketing.",
    description: "Strong marketing starts with clear messaging. We help you define your brand voice, value propositions, and key messages so every campaign communicates with clarity and consistency.",
    forWhom: "Businesses that need to sharpen their brand messaging for more effective marketing.",
    benefit: "Consistent brand voice, clearer value communication, and stronger audience connection.",
    approach: "We conduct messaging workshops, develop brand voice guidelines, craft key messages, and align all marketing communications with your brand identity.",
  },
];

export const CASE_STUDIES = [
  {
    id: "tourism-travel",
    industry: "Tourism & Travel",
    title: "Scaling a Travel Agency's Online Presence",
    objective: "Increase tour bookings and brand awareness for a travel and tours company through targeted social media marketing.",
    solution: "Developed a multi-platform Facebook and Instagram campaign strategy featuring destination visuals, lead generation forms, and retargeting sequences for website visitors.",
    services: ["Social Media Marketing Strategy", "Facebook Advertising", "Instagram Advertising", "Creative Design for Ads", "Lead Generation Campaigns"],
    result: "Improved booking inquiries and expanded reach to new audience segments through refined targeting and creative optimization.",
    platforms: ["Facebook Ads", "Instagram Ads"],
  },
  {
    id: "ecommerce-fashion",
    industry: "E-commerce / Fashion",
    title: "E-commerce Sales Boost for a Clothing Brand",
    objective: "Increase online sales and expand customer base through targeted social media advertising for a fashion e-commerce store.",
    solution: "Built a full-funnel campaign with product catalog ads, dynamic retargeting, and audience segmentation based on purchase behavior and interests.",
    services: ["Meta Ads Management", "Audience Targeting", "E-commerce Advertising Support", "Remarketing & Retargeting Campaigns"],
    result: "Improved overall sales volume and reduced customer acquisition cost through refined targeting and creative testing.",
    platforms: ["Facebook Ads", "Instagram Ads"],
  },
  {
    id: "education-consultancy",
    industry: "Education",
    title: "Education Consultancy Lead Funnel Design",
    objective: "Generate qualified leads for an education consultancy through a structured marketing funnel.",
    solution: "Created a lead generation funnel with awareness campaigns, consideration-stage content, and lead form ads with follow-up sequences.",
    services: ["Lead Generation Campaigns", "Ad Copywriting", "Conversion Funnel Strategy", "Campaign Setup & Optimization"],
    result: "Established a reliable lead pipeline with improved lead quality and lower cost per inquiry over successive campaign cycles.",
    platforms: ["Facebook Ads"],
  },
  {
    id: "local-service-business",
    industry: "Local Services",
    title: "Lead Generation for a Local Service Provider",
    objective: "Generate consistent, qualified leads for a local service business through digital marketing.",
    solution: "Built a geo-targeted lead generation campaign with lead form ads, landing pages, and precise demographic targeting for the local service area.",
    services: ["Lead Generation Campaigns", "Ad Copywriting", "Campaign Setup & Optimization", "Landing Page & Creative Support"],
    result: "Established a reliable local lead pipeline with improved lead quality and consistent monthly inquiry volume.",
    platforms: ["Facebook Ads"],
  },
  {
    id: "health-wellness",
    industry: "Health & Wellness",
    title: "Brand Awareness Campaign for a Wellness Brand",
    objective: "Build brand recognition and drive initial customer acquisition for a new health and wellness product line.",
    solution: "Designed a phased awareness-to-conversion campaign with educational content, influencer-style creatives, and interest-based targeting to warm audiences before retargeting with offers.",
    services: ["Social Media Marketing Strategy", "Creative Strategy & Campaign Planning", "Instagram Advertising", "Remarketing & Retargeting Campaigns"],
    result: "Successfully built brand presence in target market, growing engaged audience and generating first wave of qualified customer leads.",
    platforms: ["Facebook Ads", "Instagram Ads"],
  },
];

export const PRICING_PLANS = [
  {
    id: "launch",
    name: "Launch",
    subtitle: "For businesses getting started with digital marketing",
    bestFor: "Startups and small businesses testing paid campaigns for the first time.",
    price: "$499",
    period: "/month",
    features: [
      "1 advertising platform (Facebook or Instagram)",
      "Up to 2 active campaigns",
      "Audience research & targeting setup",
      "Ad creative guidance",
      "Monthly performance report",
      "Email support",
    ],
    cta: "Get Started",
    popular: false,
  },
  {
    id: "scale",
    name: "Scale",
    subtitle: "For growing businesses ready to expand their reach",
    bestFor: "Growing businesses ready to invest in structured multi-campaign marketing.",
    price: "$999",
    period: "/month",
    features: [
      "Facebook & Instagram advertising",
      "Up to 5 active campaigns",
      "Advanced audience segmentation",
      "Custom ad creative production",
      "A/B testing & optimization",
      "Bi-weekly performance reports",
      "Retargeting campaigns",
      "Priority email & chat support",
    ],
    cta: "Scale Up",
    popular: true,
  },
  {
    id: "dominance",
    name: "Dominance",
    subtitle: "For established businesses demanding peak performance",
    bestFor: "Established businesses that need full-funnel strategy and dedicated management.",
    price: "$1,999",
    period: "/month",
    features: [
      "Full-funnel marketing strategy",
      "Unlimited active campaigns",
      "Complete creative production",
      "Landing page optimization support",
      "Advanced analytics & attribution",
      "Weekly performance reports & strategy calls",
      "Dedicated account manager",
      "Priority support with fast response",
    ],
    cta: "Dominate Now",
    popular: false,
  },
  {
    id: "custom",
    name: "Custom",
    subtitle: "Tailored solutions for unique business needs",
    bestFor: "Businesses with specific requirements or large-scale campaigns needing a custom approach.",
    price: "Custom",
    period: "",
    features: [
      "Customized service scope",
      "Flexible campaign management",
      "Bespoke creative & strategy",
      "Custom reporting cadence",
      "Dedicated team assignment",
      "SLA-backed support",
    ],
    cta: "Request Proposal",
    popular: false,
  },
];

export const FAQS = [
  {
    question: "What services does MPG Solution LLC provide?",
    answer: "We provide a comprehensive range of digital marketing services including social media marketing strategy, Meta Ads management, Facebook and Instagram advertising, performance marketing, lead generation campaigns, creative strategy and campaign planning, ad copywriting, creative design, audience targeting, remarketing, conversion funnel strategy, e-commerce advertising support, marketing consultation, campaign audits, and brand messaging support.",
  },
  {
    question: "Do you offer broader digital marketing support beyond Meta ads?",
    answer: "Yes. While paid social advertising on Meta platforms is one of our core strengths, we also offer strategic digital marketing services including creative strategy, campaign planning, conversion funnel design, brand messaging support, marketing consultation, and performance review services.",
  },
  {
    question: "Do you manage both Facebook and Instagram ads?",
    answer: "Yes. We manage advertising campaigns across both Facebook and Instagram, leveraging the strengths of each platform to reach your target audience effectively.",
  },
  {
    question: "Is ad spend included in your service packages?",
    answer: "No. Our service fees cover strategy, campaign management, creative production, and optimization. Ad spend is a separate budget paid directly to the advertising platforms. We help you determine the right ad spend based on your goals.",
  },
  {
    question: "What types of businesses do you work with?",
    answer: "We work with a range of businesses including e-commerce brands, local service providers, B2B companies, startups, health and wellness brands, education consultancies, hospitality businesses, and established companies looking to grow through digital marketing.",
  },
  {
    question: "What is included in campaign strategy?",
    answer: "Our campaign strategy includes audience research, competitive analysis, platform selection, campaign structure planning, creative direction, messaging development, targeting strategy, budget allocation recommendations, and a measurement framework to track performance.",
  },
  {
    question: "Can you support creative and messaging development?",
    answer: "Absolutely. We offer full creative support including ad copywriting, graphic design for ads, brand messaging development, creative strategy, and campaign concept planning to ensure your marketing communicates effectively.",
  },
  {
    question: "Do you offer monthly management?",
    answer: "Yes. All our service plans include ongoing monthly campaign management with continuous monitoring, optimization, and regular performance reporting. We also offer one-time services like campaign audits and marketing consultations.",
  },
  {
    question: "Can you build custom plans?",
    answer: "Yes. We understand that every business is different. Our Custom plan is designed for businesses with specific requirements. Contact us to discuss your needs and we'll build a tailored solution.",
  },
  {
    question: "How do I get started working with MPG Solution LLC?",
    answer: "Simply reach out through our contact form, email us at admin@adsmpg.com, or call us at +1 315 961 3832. We'll schedule a consultation to understand your goals and recommend the best approach for your business.",
  },
  {
    question: "How do reporting and optimization work?",
    answer: "We provide regular performance reports based on your plan tier. Our team monitors campaigns continuously, making data-driven adjustments to improve performance, reduce costs, and maximize your return on investment.",
  },
  {
    question: "How soon can campaigns start after onboarding?",
    answer: "Typically, campaigns can go live within 5 to 10 business days after onboarding, depending on the complexity of the strategy and creative requirements.",
  },
  {
    question: "What happens after submitting an inquiry?",
    answer: "After you submit an inquiry, a member of our team will review your message and respond within one business day. We'll schedule a discovery call to learn about your business, goals, and challenges, then recommend a tailored approach.",
  },
  {
    question: "How can I contact MPG Solution LLC?",
    answer: "You can reach us via email at admin@adsmpg.com, by phone at +1 315 961 3832, through the contact form on our website, or by visiting our office at 30 N Gould St Ste R, Sheridan, WY 82801, USA.",
  },
];

export const NAV_LINKS = [
  { label: "Home", path: "/" },
  { label: "About", path: "/about" },
  { label: "Services", path: "/services" },
  { label: "Case Studies", path: "/case-studies" },
  { label: "Pricing", path: "/pricing" },
  { label: "FAQ", path: "/faq" },
  { label: "Contact", path: "/contact" },
];