// Centralized content for MPG Solution LLC website
// Single source of truth for all text, services, FAQs, etc.

export const COMPANY = {
  name: "MPG Solution LLC",
  legalName: "MPG Solution LLC",
  tagline: "Performance-Focused Digital Advertising for Growing Businesses",
  description: "A Wyoming-registered digital advertising and marketing services company specializing in Facebook Ads, Instagram Ads, creative strategy, and performance marketing.",
  address: "30 N Gould St Ste R, Sheridan, WY 82801, USA",
  email: "info@adsmpg.com",
  website: "www.adsmpg.com",
  nature: "Digital advertising and marketing services",
  founded: "Wyoming, USA",
  owner: "Owned and operated by MPG Solution LLC.",
};

export const SERVICES = [
  {
    id: "facebook-advertising",
    title: "Facebook Advertising",
    icon: "Facebook",
    shortDesc: "Strategic Facebook ad campaigns that reach your ideal customers and drive measurable results.",
    description: "We design, launch, and optimize Facebook advertising campaigns tailored to your business goals. From awareness to conversions, every campaign is built with data-driven targeting and compelling creatives.",
    forWhom: "Businesses looking to reach targeted audiences on the world's largest social platform.",
    benefit: "Increased brand visibility, qualified leads, and higher return on ad spend.",
    approach: "We start with audience research, create compelling ad creatives, set up precise targeting, and continuously optimize based on performance data.",
  },
  {
    id: "instagram-advertising",
    title: "Instagram Advertising",
    icon: "Instagram",
    shortDesc: "Visual-first Instagram campaigns that engage audiences and convert followers into customers.",
    description: "Leverage Instagram's visual platform with ads that captivate and convert. We handle everything from creative production to audience targeting and campaign optimization.",
    forWhom: "Brands and businesses that want to connect with engaged audiences through visual storytelling.",
    benefit: "Higher engagement rates, brand awareness, and direct-response conversions.",
    approach: "We craft scroll-stopping visuals, write persuasive copy, and deploy campaigns with precise audience segmentation across Instagram's ad placements.",
  },
  {
    id: "performance-marketing",
    title: "Performance Marketing Strategy",
    icon: "TrendingUp",
    shortDesc: "Data-driven marketing strategies focused on measurable outcomes and ROI.",
    description: "Our performance marketing approach ensures every dollar spent is tracked, measured, and optimized for maximum return. We build strategies that scale with your business.",
    forWhom: "Growth-focused businesses that want clear, measurable results from their marketing investment.",
    benefit: "Transparent reporting, optimized spend, and scalable campaign frameworks.",
    approach: "We analyze your current performance, identify growth opportunities, build measurement frameworks, and implement optimization cycles.",
  },
  {
    id: "ad-copywriting",
    title: "Ad Copywriting",
    icon: "PenTool",
    shortDesc: "Persuasive ad copy that speaks to your audience and drives action.",
    description: "Words matter. Our ad copywriting service delivers compelling headlines, body copy, and calls-to-action that resonate with your target audience and drive clicks, leads, and sales.",
    forWhom: "Businesses that need high-converting ad copy for social media campaigns.",
    benefit: "Higher click-through rates, improved ad relevance scores, and better conversion rates.",
    approach: "We research your audience, study competitor messaging, and craft copy variations for testing and optimization.",
  },
  {
    id: "creative-design",
    title: "Creative Design for Ads",
    icon: "Palette",
    shortDesc: "Scroll-stopping ad creatives designed to capture attention and convert.",
    description: "Stand out in crowded feeds with professionally designed ad creatives. We produce static images, carousels, and video-ready assets that align with your brand and campaign goals.",
    forWhom: "Businesses that need professional, on-brand creative assets for their ad campaigns.",
    benefit: "Improved ad performance, consistent brand presentation, and creative variety for testing.",
    approach: "We develop creative concepts, produce multiple variations, and test different visual approaches to find what resonates best with your audience.",
  },
  {
    id: "audience-targeting",
    title: "Audience Targeting",
    icon: "Target",
    shortDesc: "Precision audience targeting to reach the right people at the right time.",
    description: "Effective advertising starts with reaching the right audience. We build detailed audience profiles and targeting strategies using demographics, interests, behaviors, and lookalike audiences.",
    forWhom: "Businesses that want to maximize ad efficiency by reaching their most valuable potential customers.",
    benefit: "Reduced wasted spend, higher conversion rates, and more qualified leads.",
    approach: "We analyze your existing customer data, build custom and lookalike audiences, layer interest and behavior targeting, and refine based on campaign performance.",
  },
  {
    id: "campaign-optimization",
    title: "Campaign Setup & Optimization",
    icon: "Settings",
    shortDesc: "Expert campaign management from setup to ongoing performance optimization.",
    description: "We handle the technical setup of your advertising campaigns and provide ongoing optimization to ensure peak performance. From pixel installation to bid strategy, every detail is managed.",
    forWhom: "Businesses that want hands-off campaign management with expert-level optimization.",
    benefit: "Properly structured campaigns, ongoing performance improvements, and time savings.",
    approach: "We set up tracking, configure campaigns according to best practices, monitor performance daily, and make data-driven adjustments to improve results.",
  },
  {
    id: "lead-generation",
    title: "Lead Generation Campaigns",
    icon: "Users",
    shortDesc: "Targeted campaigns designed to fill your pipeline with qualified leads.",
    description: "Generate a steady flow of qualified leads through strategically designed ad campaigns. We create complete lead generation funnels from ad to form to follow-up.",
    forWhom: "Service businesses, B2B companies, and any business that relies on leads for growth.",
    benefit: "Consistent lead flow, lower cost per lead, and higher lead quality.",
    approach: "We design lead magnets, build landing pages, set up lead forms, and optimize the entire funnel for maximum lead volume and quality.",
  },
  {
    id: "ecommerce-advertising",
    title: "E-commerce Advertising Support",
    icon: "ShoppingCart",
    shortDesc: "Drive online sales with targeted e-commerce advertising strategies.",
    description: "Boost your online store's revenue with advertising strategies built for e-commerce. We optimize product catalogs, dynamic ads, and retargeting campaigns to maximize sales.",
    forWhom: "Online stores and e-commerce businesses looking to increase sales through paid advertising.",
    benefit: "Higher ROAS, increased order volume, and improved customer acquisition costs.",
    approach: "We set up product catalogs, implement dynamic retargeting, create prospecting campaigns, and optimize for purchase conversions.",
  },
  {
    id: "landing-page-support",
    title: "Landing Page & Creative Support",
    icon: "Layout",
    shortDesc: "Conversion-optimized landing pages that turn ad traffic into results.",
    description: "Your ads are only as good as where they lead. We provide landing page strategy and creative support to ensure your ad traffic converts into leads, sales, or sign-ups.",
    forWhom: "Businesses running ad campaigns that need high-converting landing experiences.",
    benefit: "Higher conversion rates, better user experience, and improved campaign ROI.",
    approach: "We audit existing pages, recommend improvements, and design conversion-focused landing experiences aligned with your ad campaigns.",
  },
];

export const CASE_STUDIES = [
  {
    id: "ecommerce-fashion",
    industry: "E-commerce / Fashion",
    title: "Scaling an Online Fashion Brand",
    objective: "Increase online sales and expand customer base through targeted social media advertising.",
    solution: "Developed a multi-phase Facebook and Instagram campaign strategy with audience segmentation, dynamic product ads, and retargeting sequences.",
    services: ["Facebook Advertising", "Instagram Advertising", "Audience Targeting", "Creative Design"],
    result: "Improved overall sales volume and reduced customer acquisition cost through refined targeting and creative optimization.",
    platforms: ["Facebook Ads", "Instagram Ads"],
  },
  {
    id: "local-service-business",
    industry: "Local Services",
    title: "Lead Generation for a Service Business",
    objective: "Generate consistent, qualified leads for a local service provider through digital advertising.",
    solution: "Built a lead generation funnel with lead form ads, landing pages, and follow-up sequences. Implemented precise geographic and demographic targeting.",
    services: ["Lead Generation Campaigns", "Ad Copywriting", "Campaign Setup & Optimization"],
    result: "Established a reliable lead pipeline with improved lead quality and lower cost per lead over successive campaign cycles.",
    platforms: ["Facebook Ads"],
  },
  {
    id: "b2b-saas",
    industry: "B2B / Technology",
    title: "Building Awareness for a B2B Platform",
    objective: "Increase brand awareness and generate demo requests for a B2B software platform.",
    solution: "Created a content-driven advertising strategy combining thought-leadership creatives with targeted awareness and conversion campaigns.",
    services: ["Performance Marketing Strategy", "Creative Design for Ads", "Ad Copywriting", "Audience Targeting"],
    result: "Increased brand visibility within target markets and improved demo request volume through strategic creative and targeting refinements.",
    platforms: ["Facebook Ads", "Instagram Ads"],
  },
];

export const PRICING_PLANS = [
  {
    id: "launch",
    name: "Launch",
    subtitle: "For businesses getting started with paid advertising",
    price: "$499",
    period: "/month",
    features: [
      "1 advertising platform (Facebook or Instagram)",
      "Up to 2 active campaigns",
      "Audience research & targeting setup",
      "Ad creative guidance",
      "Monthly performance report",
      "Email support",
    ],
    cta: "Get Started",
    popular: false,
  },
  {
    id: "scale",
    name: "Scale",
    subtitle: "For growing businesses ready to expand their reach",
    price: "$999",
    period: "/month",
    features: [
      "Facebook & Instagram advertising",
      "Up to 5 active campaigns",
      "Advanced audience segmentation",
      "Custom ad creative production",
      "A/B testing & optimization",
      "Bi-weekly performance reports",
      "Retargeting campaigns",
      "Priority email & chat support",
    ],
    cta: "Scale Up",
    popular: true,
  },
  {
    id: "dominance",
    name: "Dominance",
    subtitle: "For established businesses demanding peak performance",
    price: "$1,999",
    period: "/month",
    features: [
      "Full-funnel advertising strategy",
      "Unlimited active campaigns",
      "Complete creative production",
      "Landing page optimization support",
      "Advanced analytics & attribution",
      "Weekly performance reports & strategy calls",
      "Dedicated account manager",
      "Priority support with fast response",
    ],
    cta: "Dominate Now",
    popular: false,
  },
  {
    id: "custom",
    name: "Custom",
    subtitle: "Tailored solutions for unique business needs",
    price: "Custom",
    period: "",
    features: [
      "Customized service scope",
      "Flexible campaign management",
      "Bespoke creative & strategy",
      "Custom reporting cadence",
      "Dedicated team assignment",
      "SLA-backed support",
    ],
    cta: "Request Proposal",
    popular: false,
  },
];

export const FAQS = [
  {
    question: "What services does MPG Solution LLC provide?",
    answer: "We specialize in digital advertising and marketing services, including Facebook Ads, Instagram Ads, performance marketing strategy, ad copywriting, creative design, audience targeting, campaign setup and optimization, lead generation campaigns, e-commerce advertising support, and landing page support.",
  },
  {
    question: "Do you manage both Facebook and Instagram ads?",
    answer: "Yes. We manage advertising campaigns across both Facebook and Instagram, leveraging the strengths of each platform to reach your target audience effectively.",
  },
  {
    question: "Is ad spend included in your service packages?",
    answer: "No. Our service fees cover strategy, campaign management, creative production, and optimization. Ad spend is a separate budget paid directly to the advertising platforms. We help you determine the right ad spend based on your goals.",
  },
  {
    question: "What types of businesses do you work with?",
    answer: "We work with a range of businesses including e-commerce brands, local service providers, B2B companies, startups, and established businesses looking to grow through paid digital advertising.",
  },
  {
    question: "How do I get started working with MPG Solution LLC?",
    answer: "Simply reach out through our contact form or email us at info@adsmpg.com. We'll schedule a consultation to understand your goals and recommend the best approach for your business.",
  },
  {
    question: "Do you provide creative support for ad campaigns?",
    answer: "Yes. We offer complete creative support including ad copywriting, graphic design for static and carousel ads, and creative strategy to ensure your campaigns stand out.",
  },
  {
    question: "Can you help with lead generation campaigns?",
    answer: "Absolutely. Lead generation is one of our core services. We design and manage campaigns specifically built to generate qualified leads for your business, including lead form ads, landing pages, and follow-up sequences.",
  },
  {
    question: "How do reporting and optimization work?",
    answer: "We provide regular performance reports based on your plan tier. Our team monitors campaigns continuously, making data-driven adjustments to improve performance, reduce costs, and maximize your return on investment.",
  },
  {
    question: "How soon can campaigns start after onboarding?",
    answer: "Typically, campaigns can go live within 5 to 10 business days after onboarding, depending on the complexity of the strategy and creative requirements.",
  },
  {
    question: "How can I contact MPG Solution LLC?",
    answer: "You can reach us via email at info@adsmpg.com, through the contact form on our website, or by visiting our office at 30 N Gould St Ste R, Sheridan, WY 82801, USA.",
  },
];

export const NAV_LINKS = [
  { label: "Home", path: "/" },
  { label: "About", path: "/about" },
  { label: "Services", path: "/services" },
  { label: "Case Studies", path: "/case-studies" },
  { label: "Pricing", path: "/pricing" },
  { label: "FAQ", path: "/faq" },
  { label: "Contact", path: "/contact" },
];
